FROM 370531249777.dkr.ecr.ap-south-1.amazonaws.com/golang:1.9.4
ENV NODE_ENV=production

COPY package.json .
RUN npm install

EXPOSE 80

COPY server.js .
COPY worker.js .
COPY service service
COPY util util
COPY config config

CMD [ "npm", "start" ]
